#!/bin/bash
set -x


WGET=/usr/bin/wget
OI=/var/lib/openinfoman
USERNAME=oi
BASEX=$OI/bin/basex


REPOS=("openinfoman_fhir_adapter.xqm")


for REPO in ${REPOS[@]}
do
   INST="REPO INSTALL ${OI}/repo-src/${REPO}"
   $BASEX -Vc "${INST}"
done

chown -R $USERNAME:$USERNAME $OI

$WGET --no-check-certificate http://localhost:8984/CSD/storedFunctions/reload -O  /dev/null || true
